version: '3.8'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
    depends_on:
      - zookeeper

  producer:
    build:
      context: ../
      dockerfile: docker/Dockerfile_producer
    environment:
      - API_KEY=f8545d4dcefd85b1a2225882e3d79cf5
      - KAFKA_SERVER=kafka:9092
    depends_on:
      - kafka

  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra

  consumer:
    build:
      context: ../
      dockerfile: docker/Dockerfile_consumer
    environment:
      - KAFKA_SERVER=kafka:9092
    depends_on:
      - kafka
      - cassandra

  dashboard:
    build:
      context: ../
      dockerfile: docker/Dockerfile_dashboard
    ports:
      - "8501:8501"
    depends_on:
      - kafka
      - cassandra
  
  fill_cassandra:
    build:
      context: ../
      dockerfile: docker/Dockerfile_fill_cassandra
    depends_on:
      - cassandra
